{{- range .Values.ingresses }}
{{- if .enabled -}}
{{- $ingressName := .name | default "main" -}}
{{- range .tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "shared-helm-chart.fullname" $ }}-{{ $ingressName }}-{{ .secretName }}"
  labels:
    {{- include "shared-helm-chart.labels" $ | nindent 4 }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end}}
spec:
  secretName: {{ .secretName }}
  issuerRef:
    name: {{ .issuerRef.name }}
    kind: {{ .issuerRef.kind }}
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
